Added payment/payment CRUD, Events, Saga Support and Connection to Simulation Service
MiSArch/payment pull request #2
Opened 2024-03-19 11:14 UTC by KiLanger

2024-03-20 16:28 UTC, nk-coding requested changes

2024-03-20 16:28 UTC, nk-coding commented on src/payment.gql
>  type Query {
paymentInformations and payments should also (only or additionally) be located on the user type

2024-03-20 16:28 UTC, nk-coding commented on src/payment.gql
>    """ Retrieves all payment informations matching the fitler"""
fitler

2024-03-20 16:28 UTC, nk-coding commented on src/payment-provider-connection/connector.service.ts
> +        .post(`http://localhost:7000/${endpoint}`, data)
this looks like debug code

2024-03-20 16:28 UTC, nk-coding commented on src/payment-provider-connection/payment-processors/invoice.service.ts
> +export class InvoiceService {
missing docs

2024-03-20 16:28 UTC, nk-coding commented on src/payment-provider-connection/payment-processors/invoice.service.ts
> +export class InvoiceService {
and also all other services

2024-03-20 16:28 UTC, nk-coding commented on src/payment-provider-connection/payment-provider-connection.service.ts
> +  startPaymentProcess(paymentMethod: PaymentMethod, id: string): Promise<any> {
docs

2024-03-20 16:28 UTC, nk-coding commented on src/payment/payment.service.ts
> +  buildQuery(filter: any): any {
types are needed here

2024-03-20 19:37 UTC, KiLanger commented on src/payment.gql
>    """ Retrieves all payment informations matching the fitler"""
What? It says Filter? :D

2024-03-20 20:19 UTC, nk-coding commented on src/payment.gql
>    """ Retrieves all payment informations matching the fitler"""
""" Retrieves all payment informations matching the fitler"""

2024-03-20 21:29 UTC, KiLanger commented on src/payment.gql
>  type Query {
payments is a gropius issue:
https://frontend.gropius.duckdns.org/components/e069c868-c07f-4b9c-b2d7-ad6bb2257caf/issues/0dd9ca69-0abc-4db1-84b8-2e8ca317db45

2024-03-21 07:03 UTC, nk-coding approved these changes

2024-03-21 20:52 UTC, merged